obj-$(CONFIG_CPU_HWMON) += cpu_hwmon.o

obj-$(CONFIG_LEMOTE_YEELOONG2F)	+= yeeloong_laptop.o
CFLAGS_yeeloong_laptop.o = -I$(srctree)/arch/mips/loongson/lemote-2f

obj-$(CONFIG_LEMOTE_LYNLOONG_9002)	+= lynloong_9002_pc.o
CFLAGS_yeeloong_laptop.o = -I$(srctree)/arch/mips/loongson/lemote-2f